export const startMining = '/start-mining'
export const connectToUsa = '/start-mining#pool-usa'
export const connectToEurope = '/start-mining#pool-europe'
export const connectToAsia = '/start-mining#pool-asia'
export const blocks = '/blocks'
