export const startMining = '/start-mining'
export const connectToUS = '/start-mining#united_states'
export const connectToEurope = '/start-mining#europe'
export const connectToAsia = '/start-mining#asia'
export const blocks = '/blocks'
