export * as poolEndpointsConfig from './pool-endpoints.config'
export * as tablesConfig from './tables.config'
export * as homePageConfig from './home-page.config'
export * as blocksPageConfig from './blocks-page.config'
export * as minersPageConfig from './miners-page.config'
export * as notificationsConfig from './notifications.config'
export * as paymentsPageConfig from './payments-page.config'
export * as walletPageConfig from './wallet-page.config'
